#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
makeType=${1:-libso}
set -x 

# comment out all of this if want to keep obj. files of this version
wclean field
wclean forces
wclean lagrangian
wclean utilities
wclean solvers

#------------------------------------------------------------------------------
