#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType specie
wmake $targetType thermophysicalProperties

wmake $targetType basic
wmake $targetType reactionThermo
wmake $targetType chemistryModel

wmake $targetType catalystThermo
wmake $targetType surfaceChemistryModel

wmake $targetType SLGThermo
wmake $targetType solidThermo

#------------------------------------------------------------------------------
