#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
makeType=${1:-libso}
set -x 

# comment out all of this if want to keep obj. files of this ver. -----
 ./src/Allwclean

wclean ./applications/solvers/reactingFoam
wclean ./applications/solvers/DTLreactingFoam
wclean ./applications/solvers/catalystFoam

wclean ./applications/utilities/DTMchemkinToFoam
wclean ./applications/utilities/FTMchemkinToFoam
wclean ./applications/utilities/chemkinToFoam
wclean ./applications/utilities/surfChemkinToFoam

# ----------------------------------------------------------------------
# update this lafter 
cd $FOAM_USER_LIBBIN

rm -rf libcatSpecie.so
rm -rf libthermophysicalProperties.so
rm -rf libfluidThermophysicalModels.so
rm -rf libreactionThermophysicalModels.so
rm -rf libcatReactionThermophysicalModels.so
rm -rf libchemistryModel.so
rm -rf libsurfaceChemistryModel.so
rm -rf libsolidThermo.so
rm -rf libSLGThermo.so
rm -rf libfluidThermoMomentumTransportModels.so
rm -rf libthermophysicalTransportModels.so
rm -rf libpsiReactionThermophysicalTransportModels.so
rm -rf librhoReactionThermophysicalTransportModels.so
rm -rf libradiationModels.so
rm -rf libcombustionModels.so
rm -rf libfvOptions.so
rm -rf libspecieTransfer.so
rm -rf libcatalyticSurfaceFvPatchFields.so
rm -rf libsurfaceFilmModels.so
rm -rf libsurfaceFilmDerivedFvPatchFields.so
rm -rf libthermalBaffleModels.so
rm -rf libfieldFunctionObjects.so
rm -rf libforces.so
rm -rf liblagrangianFunctionObjects.so
rm -rf libsolverFunctionObjects.so
rm -rf libutilityFunctionObjects.so

cd - 

cd $FOAM_USER_APPBIN

rm -rf DTLreactingFoam*
rm -rf reactingFoam*
rm -rf catalystFoam

rm -rf chemkinToFoam*
rm -rf DTMchemkinToFoam*
rm -rf FTMchemkinToFoam*
rm -rf surfChemkinToFoam*

cd - 

#------------------------------------------------------------------------------
