#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

src/Allwmake $targetType $*

wmake $targetType applications/solvers/reactingFoam
wmake $targetType applications/solvers/DTLreactingFoam
wmake $targetType applications/solvers/catalystFoam

wmake $targetType applications/utilities/chemkinToFoam
wmake $targetType applications/utilities/DTMchemkinToFoam
wmake $targetType applications/utilities/FTMchemkinToFoam
wmake $targetType applications/utilities/surfChemkinToFoam

#------------------------------------------------------------------------------
