#!/bin/bash

cd "${0%/*}" || exit 1

# remove the data
rm -rf thermo.surf.const
rm -rf reactions.surf

echo "Clean up completed."
#------------------------------------------------------------------------------
