#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

thermophysicalModels/Allwmake $targetType $*
MomentumTransportModels/Allwmake $targetType $*
ThermophysicalTransportModels/Allwmake $targetType $*
wmake $targetType radiationModels
wmake $targetType combustionModels
wmake $targetType fvOptions
wmake $targetType specieTransfer
wmake $targetType catalyticSurfaceBoundaries

regionModels/Allwmake $targetType $*
functionObjects/Allwmake $targetType $*

#------------------------------------------------------------------------------
